server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogging_application
    username: root
    password: Shubham3417@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #create and update tables in the database if required can also be create/create-drop or validate
    show-sql: true